terraform {
  required_providers {
    spotify = {
      source  = "conradludgate/spotify"
      version = "0.2.7"
    }
  }
}

# Configure the provider with the API key retrieved from the auth proxy
provider "spotify" {
  api_key = var.spotify_api_key
}

# Variable configuration
variable "spotify_api_key" {
  type        = string
  description = "The API key generated by the spotify-auth-proxy container"
  sensitive   = true
}

# Data source: Search for an artist to dynamically find tracks
data "spotify_search_track" "daft_punk" {
  artist = "Daft Punk"
  limit  = 3
}

# Resource: Create a public Spotify playlist
resource "spotify_playlist" "synth_wave" {
  name        = "Terraform Synth Wave"
  description = "This playlist was entirely managed and provisioned using Terraform."
  public      = true

  # Combine individual track IDs and dynamically discovered tracks
  tracks = [
    data.spotify_search_track.daft_punk.tracks[0].id,
    data.spotify_search_track.daft_punk.tracks[1].id,
    "4PTG3Z6ehGkBFm3qLwg8S6" # Example hardcoded Track ID (Rick Astley)
  ]
}
